# 1. Khởi tạo môi trường & Đọc dữ liệu

In [1]:
# export
import re
import pandas as pd
from helpers.get_configs import get_config

RAW_DATA_PATH = get_config('dirs.yaml', ['raw_data', 'majors'], as_path=True)
CLEANED_DATA_PATH = get_config('dirs.yaml', ['cleaned_data', 'majors'], as_path=True)
SCRIPT_OUTPUT_PATH = get_config('dirs.yaml', ['unit_scripts', 'majors'], as_path=True)

# Đọc file CSV vào DataFrame
df = pd.read_parquet(RAW_DATA_PATH)

In [2]:
# Khảo sát thông tin tổng quan của dữ liệu
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   major_group_id     506 non-null    int64
 1   major_group_name   506 non-null    str
 2   major_id           506 non-null    int64
 3   major_name         506 non-null    str
 4   major_description  506 non-null    str
 5   score_codes        506 non-null    str
dtypes: int64(2), str(4)
memory usage: 274.7 KB

,major_group_id,major_group_name,major_id,major_name,major_description,score_codes
0,1,Kế toán - Kiểm toán,910,Quản trị tài chính kế toán,Quản trị tài chính kế toán,D404; 7340101_02
1,1,Kế toán - Kiểm toán,1,Kế toán,Tài chính và Kế toán (BFA); Kế toán; Kế toán d...,7340301; 7340301DKD; 7340301DKK; 7340301DL; 73...
2,1,Kế toán - Kiểm toán,2,Kiểm toán,Kế toán kiểm toán (ngành Kế toán); Kiểm toán (...,7340302; 7340302DKD; 7340302DKK; 7340302_409; ...
3,2,Tài chính - Ngân hàng - Bảo hiểm,904,Kinh tế và quản lý bất động sản,Kinh tế và quản lý bất động sản,GTADCKB2
4,2,Tài chính - Ngân hàng - Bảo hiểm,3,Tài chính,Tài chính doanh nghiệp (theo định hướng ACCA);...,"TM24, TM25, TM26, TM27; 7340201QT01.11; EP10; ..."

# 2. Kiểm tra giá trị rỗng

In [3]:
# Kiểm tra số lượng giá trị rỗng trên các cột
df.isna().sum()

major_group_id       0
major_group_name     0
major_id             0
major_name           0
major_description    0
score_codes          0
dtype: int64

**Kết luận**: Các cột bị thiếu dữ liệu đều thuộc về `major_description` là cột không quan trọng, nên không cần bổ sung / lược bỏ các hàng này.

# 3. Chuẩn hóa danh sách và chuỗi

In [4]:
# export
def remove_newlines(val):
    if pd.isna(val):
        return val
    if isinstance(val, str):
        return re.sub(r'[\r\n]+', ' ', val).strip()
    return val

df = df.map(remove_newlines)

def normalize_score_codes(val):
    if pd.isna(val) or str(val).strip() == '':
        return val
    s = str(val).replace(',', ';')
    s = re.sub(r'\s+', '', s)
    return s

df['score_codes'] = df['score_codes'].apply(normalize_score_codes)

# 4. Lưu dữ liệu đã làm sạch

In [5]:
# export
CLEANED_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(CLEANED_DATA_PATH, index=False)

In [6]:
# Khảo sát dữ liệu sau khi lưu
print(f"Tổng số dòng sau chuẩn hóa: {len(df)}")
df.info()
df.head()

Tổng số dòng sau chuẩn hóa: 506
<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   major_group_id     506 non-null    int64
 1   major_group_name   506 non-null    str
 2   major_id           506 non-null    int64
 3   major_name         506 non-null    str
 4   major_description  506 non-null    str
 5   score_codes        506 non-null    str
dtypes: int64(2), str(4)
memory usage: 271.3 KB

,major_group_id,major_group_name,major_id,major_name,major_description,score_codes
0,1,Kế toán - Kiểm toán,910,Quản trị tài chính kế toán,Quản trị tài chính kế toán,D404;7340101_02
1,1,Kế toán - Kiểm toán,1,Kế toán,Tài chính và Kế toán (BFA); Kế toán; Kế toán d...,7340301;7340301DKD;7340301DKK;7340301DL;734030...
2,1,Kế toán - Kiểm toán,2,Kiểm toán,Kế toán kiểm toán (ngành Kế toán); Kiểm toán (...,7340302;7340302DKD;7340302DKK;7340302_409;ACT0...
3,2,Tài chính - Ngân hàng - Bảo hiểm,904,Kinh tế và quản lý bất động sản,Kinh tế và quản lý bất động sản,GTADCKB2
4,2,Tài chính - Ngân hàng - Bảo hiểm,3,Tài chính,Tài chính doanh nghiệp (theo định hướng ACCA);...,TM24;TM25;TM26;TM27;7340201QT01.11;EP10;734020...

# 5. Xuất Notebook sang Unit Script

In [7]:
from helpers.export_to_script import export_to_script

export_to_script(output_path=SCRIPT_OUTPUT_PATH)

Đã xuất 3 cell từ 'majors.ipynb' sang 'D:\UNIDOCS\IS405.R11-Big-Data\scripts-processing\unit-scripts\majors.py'

'D:\\UNIDOCS\\IS405.R11-Big-Data\\scripts-processing\\unit-scripts\\majors.py'