# 1. Khởi tạo môi trường & Đọc dữ liệu

In [17]:
# export
import json
import random
import re
import time
from urllib.parse import quote

import pandas as pd
import requests
from pytrends.request import TrendReq

from helpers.get_configs import get_config

MAJORS_PATH = get_config('dirs.yaml', ['cleaned_data', 'majors'], as_path=True)
CUTOFF_SCORES_PATH = get_config('dirs.yaml', ['cleaned_data', 'cutoff_scores'], as_path=True)
SCORE_BLOCKS_PATH = get_config('dirs.yaml', ['cleaned_data', 'score_blocks'], as_path=True)
TOPICS_PATH = get_config('dirs.yaml', ['raw_data', 'trend_topics'], as_path=True)
SCRIPT_OUTPUT_PATH = get_config('dirs.yaml', ['unit_scripts', 'get_topics'], as_path=True)

df_majors = pd.read_csv(MAJORS_PATH, encoding='utf-8', usecols=['major_group_name', 'major_name'])
df_cutoff = pd.read_csv(CUTOFF_SCORES_PATH, encoding='utf-8', usecols=['school_name', 'score_admission_name'])
df_blocks = pd.read_csv(SCORE_BLOCKS_PATH, encoding='utf-8')

In [18]:
# Khảo sát thông tin tổng quan của dữ liệu
df_majors.info()
df_cutoff.info()
df_blocks.info()
df_blocks.head()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   major_group_name  506 non-null    str
 1   major_name        506 non-null    str
dtypes: str(2)
memory usage: 38.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 101466 entries, 0 to 101465
Data columns (total 2 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   school_name           101466 non-null  str
 1   score_admission_name  101466 non-null  str
dtypes: str(2)
memory usage: 7.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      280 non-null    str
 1   subject1  280 non-null    str
 2   subject2  280 non-null    str
 3   subject3  280 non-null    str
 4   subject4  1 non-null      str
dtypes: str(5)
memory usage: 21.8 KB

  code subject1 subject2   subject3 subject4
0  D01     Toán  Ngữ văn  Tiếng anh      NaN
1  A00     Toán   Vật lí    Hóa học      NaN
2  A01     Toán   Vật lí  Tiếng anh      NaN
3  D07     Toán  Hóa học  Tiếng anh      NaN
4  B00     Toán  Hóa học   Sinh học      NaN

# 2. Thành lập danh sách unique

In [19]:
# export
def unique_values(series, sep=None):
    """Chuẩn hóa khoảng trắng, bỏ rỗng/NaN và loại trùng (không phân biệt hoa/thường), giữ nguyên thứ tự xuất hiện.
    Nếu truyền `sep`, mỗi ô sẽ được tách theo dấu phân cách đó trước khi lấy unique."""
    series = series.dropna().astype(str)
    if sep:
        series = series.str.split(sep).explode()
    cleaned = series.astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()
    seen, result = set(), []
    for value in cleaned:
        key = value.casefold()
        if value and key not in seen:
            seen.add(key)
            result.append(value)
    return result


school_names = unique_values(df_cutoff['school_name'])
major_group_names = unique_values(df_majors['major_group_name'])
major_names = unique_values(df_majors['major_name'], sep=';')   # major_name phân cách bằng ';'
admission_method_names = unique_values(df_cutoff['score_admission_name'])

## Tổ hợp môn (subject_group) & môn học (subject)

- `subject_group_name` = `subject1 - subject2 - subject3 - subject4` (bỏ qua ô rỗng), ví dụ `Toán - Vật lí - Hóa học` hoặc `Toán - Vật lí - Hóa học - Sinh học`.
- `subject_names` = unique của toàn bộ các cột `subject1..subject4`.

In [20]:
# export
SUBJECT_COLUMNS = ['subject1', 'subject2', 'subject3', 'subject4']
SUBJECT_GROUP_COLUMNS = ['subject1', 'subject2', 'subject3', 'subject4']


def build_subject_group_name(row):
    parts = [re.sub(r'\s+', ' ', str(row[c])).strip() for c in SUBJECT_GROUP_COLUMNS if pd.notna(row[c])]
    parts = [p for p in parts if p]
    return ' - '.join(parts)


subject_group_names = unique_values(df_blocks.apply(build_subject_group_name, axis=1))
subject_names = unique_values(df_blocks[SUBJECT_COLUMNS].stack())   # stack() tự bỏ NaN

print(f"school_names:           {len(school_names)}")
print(f"major_group_names:      {len(major_group_names)}")
print(f"major_names:            {len(major_names)}")
print(f"admission_method_names: {len(admission_method_names)}")
print(f"subject_group_names:    {len(subject_group_names)}")
print(f"subject_names:          {len(subject_names)}")

school_names:           302
major_group_names:      36
major_names:            451
admission_method_names: 13
subject_group_names:    274
subject_names:          80

In [21]:
# Xem nhanh các danh sách
for name, values in [('school', school_names), ('major_group', major_group_names),
                     ('major', major_names), ('admission_method', admission_method_names),
                     ('subject_group', subject_group_names), ('subject', subject_names)]:
    print(f"--- {name} ---")
    print(values[:5])

--- school ---
['Trường Cao Đẳng Kỹ Thuật Cao Thắng', 'Trường Cao Đẳng Công Thương TPHCM', 'Đại Học Kinh Tế Quốc Dân', 'Đại Học Bách Khoa Hà Nội', 'Học Viện Tài chính']
--- major_group ---
['Kế toán - Kiểm toán', 'Tài chính - Ngân hàng - Bảo hiểm', 'Kinh tế - Quản trị kinh doanh - Thương Mại', 'Công nghệ thông tin - Tin học', 'Công nghiệp bán dẫn']
--- major ---
['Quản trị tài chính kế toán', 'Kế toán', 'Kiểm toán', 'Kinh tế và quản lý bất động sản', 'Tài chính']
--- admission_method ---
['Điểm thi THPT', 'Điểm học bạ', 'Điểm ĐGNL V-ACT', 'Điểm ĐGNL HSA', 'Điểm ĐGTD TSA']
--- subject_group ---
['Toán - Ngữ văn - Tiếng anh', 'Toán - Vật lí - Hóa học', 'Toán - Vật lí - Tiếng anh', 'Toán - Hóa học - Tiếng anh', 'Toán - Hóa học - Sinh học']
--- subject ---
['Toán', 'Ngữ văn', 'Tiếng anh', 'Vật lí', 'Hóa học']

# 3. Cấu hình & cơ chế lấy topic (có fallback)

Chuỗi fallback cho mỗi keyword:

1. `pytrends.suggestions()` — thử lại tối đa `MAX_RETRIES` lần (timeout + exponential backoff có jitter).
2. Nếu vẫn lỗi: **gửi request thủ công** bằng `requests.Session` tới đúng endpoint autocomplete của Google Trends (cùng `hl=vi-VN`, `tz=-420`), cũng thử lại tối đa `MAX_RETRIES` lần.
3. Mỗi lần chuyển bước hoặc gặp HTTP 429 sẽ **tạo lại session/cookie**.
4. Nếu liên tiếp nhiều keyword thất bại thì nghỉ dài (`COOLDOWN_SECONDS`) rồi chạy tiếp.

> Lưu ý: endpoint autocomplete của Google Trends **không có tham số `geo`**, nên "địa điểm Việt Nam" được áp dụng qua `hl='vi-VN'` và `tz=-420` (UTC+7).

In [22]:
# export
# --- Địa điểm / ngôn ngữ: Việt Nam ---
HL = 'vi-VN'
TZ = -420                      # UTC+7, tính theo phút (pytrends dùng giá trị âm cho múi giờ phía Đông)

# --- Timeout / retry ---
REQUEST_TIMEOUT = (5, 15)      # (connect, read) giây
MAX_RETRIES = 3                # số lần thử cho MỖI phương thức (pytrends, thủ công)
BACKOFF_BASE = 2               # chờ = BACKOFF_BASE ** lần_thử + jitter
RATE_LIMIT_MULTIPLIER = 2      # nhân thời gian chờ khi gặp 429
SLEEP_RANGE = (1.0, 2.5)       # nghỉ ngẫu nhiên giữa 2 keyword thành công
CONSECUTIVE_FAIL_LIMIT = 3
COOLDOWN_SECONDS = 60

SUGGESTIONS_URL = 'https://trends.google.com/trends/api/autocomplete/'
OUTPUT_COLUMNS = ['keyword', 'keyword_type', 'mid', 'title', 'type']
USER_AGENT = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
              '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36')

In [23]:
# export
class FetchError(Exception):
    """Mọi phương thức/lần thử đều thất bại cho một keyword."""


def _is_rate_limited(error):
    msg = str(error)
    return '429' in msg or 'Too Many Requests' in msg


class TopicFetcher:
    def __init__(self):
        self.preferred = 'pytrends'   # phương thức vừa thành công gần nhất sẽ được thử trước
        self._reset()

    # ---------- khởi tạo / làm mới session ----------
    def _reset(self):
        try:
            # Lưu ý: không truyền retries/backoff_factor vào TrendReq vì pytrends cũ
            # lỗi với urllib3>=2 (method_whitelist). Tự retry ở bên dưới.
            self.pytrends = TrendReq(hl=HL, tz=TZ, timeout=REQUEST_TIMEOUT)
        except Exception as e:
            print(f"  [warn] Không khởi tạo được TrendReq: {e}")
            self.pytrends = None

        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': USER_AGENT,
            'Accept-Language': 'vi-VN,vi;q=0.9,en;q=0.5',
            'Accept': 'application/json, text/plain, */*',
        })
        try:  # lấy cookie (NID...) giống trình duyệt
            self.session.get('https://trends.google.com/trends/?geo=VN',
                             timeout=REQUEST_TIMEOUT)
        except Exception as e:
            print(f"  [warn] Không lấy được cookie: {e}")

    # ---------- phương thức 1: pytrends ----------
    def _via_pytrends(self, keyword):
        if self.pytrends is None:
            raise RuntimeError('pytrends chưa khởi tạo')
        return self.pytrends.suggestions(keyword=keyword)

    # ---------- phương thức 2: request thủ công ----------
    def _via_manual(self, keyword):
        url = SUGGESTIONS_URL + quote(keyword, safe='')
        resp = self.session.get(url, params={'hl': HL, 'tz': TZ}, timeout=REQUEST_TIMEOUT)
        if resp.status_code == 429:
            raise requests.HTTPError('429 Too Many Requests', response=resp)
        resp.raise_for_status()
        # Google thêm tiền tố chống XSSI ")]}'," trước JSON
        text = re.sub(r"^\)\]\}',?\s*", '', resp.text)
        return json.loads(text)['default']['topics']

    # ---------- điều phối + fallback ----------
    def fetch(self, keyword):
        methods = [('pytrends', self._via_pytrends), ('manual', self._via_manual)]
        methods.sort(key=lambda m: m[0] != self.preferred)   # phương thức ưu tiên lên đầu
        last_error = None
        for method_name, method in methods:
            for attempt in range(1, MAX_RETRIES + 1):
                try:
                    topics = method(keyword)
                    self.preferred = method_name
                    return [t for t in (topics or []) if isinstance(t, dict)]
                except Exception as e:
                    last_error = e
                    wait = BACKOFF_BASE ** attempt + random.uniform(0, 1)
                    if _is_rate_limited(e):
                        wait *= RATE_LIMIT_MULTIPLIER
                    print(f"  [{method_name}] lần {attempt}/{MAX_RETRIES} lỗi: {e!r} -> chờ {wait:.1f}s")
                    time.sleep(wait)
                    if _is_rate_limited(e):
                        self._reset()          # đổi cookie/session khi bị chặn
            print(f"  [{method_name}] hết lượt thử, chuyển phương thức kế tiếp")
            self._reset()
        raise FetchError(f"{keyword!r}: {last_error!r}")

# 4. Chuẩn bị danh sách keyword

In [24]:
# export
keyword_sources = {
    'school': school_names,
    'major_group': major_group_names,
    'major': major_names,
    'admission_method': admission_method_names,
    'subject_group': subject_group_names,
    'subject': subject_names,
}

tasks = [(ktype, kw) for ktype, kws in keyword_sources.items() for kw in kws]

print(f"Tổng số keyword: {len(tasks)}")
print({k: len(v) for k, v in keyword_sources.items()})

Tổng số keyword: 1156
{'school': 302, 'major_group': 36, 'major': 451, 'admission_method': 13, 'subject_group': 274, 'subject': 80}

# 5. Lấy danh sách topic từ Google Trends

In [25]:
# export
rows = []
failed = []
no_result = []
fetcher = TopicFetcher()
consecutive_fails = 0

for i, (ktype, keyword) in enumerate(tasks, start=1):
    try:
        topics = fetcher.fetch(keyword)
        for topic in topics:
            rows.append({
                'keyword': keyword,
                'keyword_type': ktype,
                'mid': topic.get('mid'),
                'title': topic.get('title'),
                'type': topic.get('type'),
            })
        if not topics:
            no_result.append((ktype, keyword))
        consecutive_fails = 0
        print(f"[{i}/{len(tasks)}] ({ktype}) {keyword} -> {len(topics)} topic")
        time.sleep(random.uniform(*SLEEP_RANGE))
    except FetchError as e:
        failed.append((ktype, keyword))
        consecutive_fails += 1
        print(f"[{i}/{len(tasks)}] THẤT BẠI: {e}")
        if consecutive_fails >= CONSECUTIVE_FAIL_LIMIT:
            print(f"  Thất bại liên tiếp {consecutive_fails} lần -> nghỉ {COOLDOWN_SECONDS}s")
            time.sleep(COOLDOWN_SECONDS)
            fetcher._reset()
            consecutive_fails = 0

df_topics = pd.DataFrame(rows, columns=OUTPUT_COLUMNS)
df_topics = df_topics.drop_duplicates(subset=['keyword', 'keyword_type', 'mid'])

TOPICS_PATH.parent.mkdir(parents=True, exist_ok=True)
df_topics.to_csv(TOPICS_PATH, index=False, encoding='utf-8')
print(f"Hoàn tất. Số dòng: {len(df_topics)} | Không có topic: {len(no_result)} | Thất bại: {len(failed)}")
if failed:
    print("Keyword thất bại:", failed)

[1/1156] (school) Trường Cao Đẳng Kỹ Thuật Cao Thắng -> 3 topic
[2/1156] (school) Trường Cao Đẳng Công Thương TPHCM -> 4 topic
[3/1156] (school) Đại Học Kinh Tế Quốc Dân -> 3 topic
[4/1156] (school) Đại Học Bách Khoa Hà Nội -> 5 topic
[5/1156] (school) Học Viện Tài chính -> 4 topic
[6/1156] (school) Học Viện Ngân Hàng -> 3 topic
[7/1156] (school) Trường Đại học Ngoại thương -> 3 topic
[8/1156] (school) Trường Đại Học Bách Khoa HCM -> 4 topic
[9/1156] (school) Trường Đại Học Y Hà Nội -> 5 topic
[10/1156] (school) Học Viện Công Nghệ Bưu Chính Viễn Thông -> 5 topic
[11/1156] (school) Trường Đại Học Sư Phạm Hà Nội -> 5 topic
[12/1156] (school) Trường Đại Học Thương Mại -> 3 topic
[13/1156] (school) Trường Đại Học Sư Phạm TPHCM -> 4 topic
[14/1156] (school) Đại Học Y Dược TPHCM -> 2 topic
[15/1156] (school) Trường Đại Học Công Nghệ – Đại Học Quốc Gia Hà Nội -> 5 topic
[16/1156] (school) Trường Đại học Thủ Đô Hà Nội -> 3 topic
[17/1156] (school) Trường Đại Học Giao Thông Vận Tải -> 5 topic
[18/1156] (school) Trường Đại Học Y Dược Thái Bình -> 0 topic
[19/1156] (school) Học Viện Kỹ Thuật Mật Mã -> 1 topic
[20/1156] (school) Đại Học Công Nghiệp Hà Nội -> 3 topic
[21/1156] (school) Trường Đại Học Y Dược Hải Phòng -> 1 topic
[22/1156] (school) Trường Đại Học Công Nghiệp TPHCM -> 5 topic
[23/1156] (school) Học Viện Phụ Nữ Việt Nam -> 0 topic
[24/1156] (school) Trường Đại Học Dược Hà Nội -> 3 topic
[25/1156] (school) Học Viện An Ninh Nhân Dân -> 2 topic
[26/1156] (school) Trường Đại Học Kỹ Thuật Y Tế Hải Dương -> 2 topic
[27/1156] (school) Trường Đại Học Giao Thông Vận Tải TPHCM -> 2 topic
[28/1156] (school) Học Viện Y Dược Học Cổ Truyền Việt Nam -> 1 topic
[29/1156] (school) Học Viện Cảnh Sát Nhân Dân -> 1 topic
[30/1156] (school) Trường Đại Học Kinh Tế Kỹ Thuật Công Nghiệp -> 5 topic
[31/1156] (school) Trường Đại Học Công Thương TPHCM -> 2 topic
[32/1156] (school) Trường Sĩ Quan Lục Quân 1 - Đại học Trần Quốc Tuấn -> 1 topic
[33/1156] (school) Học Viện Hải Quân -> 5 topic
[34/1156] (school) Học Viện Hàng không Việt Nam -> 4 topic
[35/1156] (school) Đại Học Phenikaa -> 5 topic
[36/1156] (school) Học Viện Phòng Không – Không Quân -> 3 topic
[37/1156] (school) Trường Đại Học Cảnh Sát Nhân Dân -> 5 topic
[38/1156] (school) Trường Sĩ Quan Thông Tin - Hệ Quân sự - Đại Học Thông Tin Liên Lạc -> 0 topic
[39/1156] (school) Trường Đại Học Hà Nội -> 5 topic
[40/1156] (school) Học Viện Kỹ Thuật Quân Sự - Hệ Quân sự -> 4 topic
[41/1156] (school) Trường Đại Học Y Tế Công Cộng -> 3 topic
[42/1156] (school) Học Viện Ngoại Giao -> 4 topic
[43/1156] (school) Trường Đại Học An Ninh Nhân Dân -> 1 topic
[44/1156] (school) Trường Đại Học Y Dược Cần Thơ -> 1 topic
[45/1156] (school) Trường Đại học Thủ Dầu Một -> 1 topic
[46/1156] (school) Trường Đại Học Y Khoa Phạm Ngọc Thạch -> 2 topic
[47/1156] (school) Trường Đại Học Thăng Long -> 1 topic
[48/1156] (school) Trường Đại Học Thủy Lợi -> 5 topic
[49/1156] (school) Trường Đại Học Khoa Học Tự Nhiên TPHCM -> 2 topic
[50/1156] (school) Trường Đại Học Văn Hóa Hà Nội -> 1 topic
[51/1156] (school) Trường Đại Học Tôn Đức Thắng -> 3 topic
[52/1156] (school) Học Viện Nông Nghiệp Việt Nam -> 4 topic
[53/1156] (school) Trường Đại Học Khoa Học Xã Hội và Nhân Văn Hà Nội -> 3 topic
[54/1156] (school) Trường Đại Học Luật Hà Nội -> 2 topic
[55/1156] (school) Trường Đại Học Ngoại Ngữ - ĐH Quốc gia Hà Nội -> 1 topic
[56/1156] (school) Học viện Báo chí và Tuyên truyền -> 1 topic
[57/1156] (school) Trường Đại Học Khoa Học Tự Nhiên Hà Nội -> 2 topic
[58/1156] (school) Trường Đại Học Kinh Tế - ĐHQG Hà Nội -> 0 topic
[59/1156] (school) Trường Đại Học Khoa Học Xã Hội và Nhân Văn TPHCM -> 0 topic
[60/1156] (school) Đại Học Sư Phạm Thái Nguyên -> 1 topic
[61/1156] (school) Trường Sĩ Quan Chính Trị - Đại Học Chính Trị -> 5 topic
[62/1156] (school) Đại Học Cần Thơ -> 5 topic
[63/1156] (school) Trường Đại học Kiểm Sát -> 0 topic
[64/1156] (school) Học Viện Biên Phòng -> 2 topic
[65/1156] (school) Trường Đại học Luật – ĐHQG Hà Nội -> 0 topic
[66/1156] (school) Trường Đại Học Sư Phạm Huế -> 1 topic
[67/1156] (school) Trường Đại Học Công Nghệ Thông Tin - ĐHQG TPHCM -> 1 topic
[68/1156] (school) Trường Đại Học Sài Gòn -> 5 topic
[69/1156] (school) Học Viện Khoa Học Quân Sự - Hệ Quân sự -> 5 topic
[70/1156] (school) Trường Đại học Ngoại thương (Cơ sở II) -> 2 topic
[71/1156] (school) Học viện Tòa án -> 5 topic
[72/1156] (school) Trường Đại Học Sư Phạm - Đại Học Đà Nẵng -> 3 topic
[73/1156] (school) Trường Đại Học Sư Phạm Hà Nội 2 -> 2 topic
[74/1156] (school) Trường Đại Học Giáo Dục - ĐHQG Hà Nội -> 2 topic
[75/1156] (school) Trường Đại Học Văn Hóa TPHCM -> 2 topic
[76/1156] (school) Trường Đại Học Công nghệ Kỹ thuật TP HCM -> 1 topic
[77/1156] (school) Học Viện Thanh Thiếu Niên Việt Nam -> 1 topic
[78/1156] (school) Học Viện Quân Y - Hệ Quân sự -> 5 topic
[79/1156] (school) Trường Đại học Kinh Tế Luật TPHCM -> 0 topic
[80/1156] (school) Học Viện Hậu Cần - Hệ Quân sự -> 1 topic
[81/1156] (school) Trường Đại Học Luật TPHCM -> 2 topic
[82/1156] (school) Trường Đại Học Ngoại Ngữ Đà Nẵng -> 3 topic
[83/1156] (school) Đại Học Kinh Tế TPHCM -> 5 topic
[84/1156] (school) Trường Đại học Y Dược - ĐHQG Hà Nội -> 0 topic
[85/1156] (school) Trường Đại Học Bách Khoa Đà Nẵng -> 4 topic
[86/1156] (school) Trường Đại Học Ngoại Ngữ Huế -> 1 topic
[87/1156] (school) Trường Đại Học Tài Chính Marketing -> 5 topic
[88/1156] (school) Trường Đại Học Giao Thông Vận Tải (Cơ sở 2) -> 3 topic
[89/1156] (school) Trường Đại Học Nha Trang -> 4 topic
[90/1156] (school) Trường Sĩ Quan Lục Quân 2 - Đại học Nguyễn Huệ -> 1 topic
[91/1156] (school) Học Viện Công Nghệ Bưu Chính Viễn Thông (Cơ sở TP.HCM) -> 3 topic
[92/1156] (school) Trường Đại Học Y Khoa Vinh -> 4 topic
[93/1156] (school) Trường Đại học Kỹ thuật Y Dược Đà Nẵng -> 3 topic
[94/1156] (school) Trường Đại Học Y Dược Thái Nguyên -> 2 topic
[95/1156] (school) Trường Đại Học Y Dược Huế -> 4 topic
[96/1156] (school) Trường Y Dược Đà Nẵng -> 2 topic
[97/1156] (school) Trường Đại Học Kiến Trúc TPHCM -> 2 topic
[98/1156] (school) Học Viện Chính Trị Công An Nhân Dân -> 5 topic
[99/1156] (school) Trường Đại học Khoa học sức khỏe TPHCM -> 3 topic
[100/1156] (school) Trường Đại Học Quốc Tế - ĐHQG TPHCM -> 2 topic
[101/1156] (school) Trường Đại Học Hùng Vương -> 2 topic
[102/1156] (school) Trường Đại Học Hải Phòng -> 2 topic
[103/1156] (school) Học Viện Chính Sách và Phát Triển -> 3 topic
[104/1156] (school) Trường Đại Học Mở Hà Nội -> 4 topic
[105/1156] (school) Trường Đại Học Công Đoàn -> 2 topic
[106/1156] (school) Trường Đại Học Hàng Hải Việt Nam -> 4 topic
[107/1156] (school) Trường Đại Học Kiến Trúc Hà Nội -> 0 topic
[108/1156] (school) Trường Đại Học Vinh -> 5 topic
[109/1156] (school) Trường Đại Học An Giang -> 3 topic
[110/1156] (school) Học Viện Hành Chính và Quản trị công -> 4 topic
[111/1156] (school) Trường Đại Học Đồng Tháp -> 1 topic
[112/1156] (school) Trường Khoa học liên ngành và Nghệ thuật Hà Nội -> 3 topic
[113/1156] (school) Trường Đại Học Tây Nguyên -> 2 topic
[114/1156] (school) Trường Đại Học Quy Nhơn -> 1 topic
[115/1156] (school) Khoa Giáo Dục Thể Chất Huế -> 3 topic
[116/1156] (school) Trường Đại Học Sư Phạm Nghệ Thuật Trung Ương -> 2 topic
[117/1156] (school) Trường Đại Học Kinh Tế – Đại Học Đà Nẵng -> 2 topic
[118/1156] (school) Trường Ngoại Ngữ Thái Nguyên -> 1 topic
[119/1156] (school) Trường Đại Học Hạ Long -> 3 topic
[120/1156] (school) Trường Đại Học Hải Dương -> 5 topic
[121/1156] (school) Trường Đại Học Quảng Bình -> 3 topic
[122/1156] (school) Trường Đại Học Phạm Văn Đồng -> 5 topic
[123/1156] (school) Trường Đại Học Hà Tĩnh -> 1 topic
[124/1156] (school) Trường Đại học Tài Nguyên và Môi Trường Hà Nội -> 4 topic
[125/1156] (school) Học Viện Hành Chính Và Quản Trị Công (phía Nam) -> 0 topic
[126/1156] (school) Trường Đại Học Ngân Hàng TPHCM -> 3 topic
[127/1156] (school) Trường Đại Học Lao Động – Xã Hội -> 3 topic
[128/1156] (school) Trường Đại Học Bạc Liêu -> 3 topic
[129/1156] (school) Trường Đại Học Quảng Nam -> 5 topic
[130/1156] (school) Trường Đại Học Lao Động – Xã Hội (Cơ sở II) -> 1 topic
[131/1156] (school) Trường Đại Học Phú Yên -> 2 topic
[132/1156] (school) Phân Hiệu Đại Học Đà Nẵng tại Kon Tum -> 2 topic
[133/1156] (school) Trường Đại Học Sư Phạm Thể Dục Thể Thao Hà Nội -> 1 topic
[134/1156] (school) Trường Đại học Kỹ Thuật Công Nghệ Cần Thơ -> 2 topic
[135/1156] (school) Trường Quốc Tế - ĐHQG Hà Nội -> 1 topic
[136/1156] (school) Trường Đại Học Khoa Học Và Công Nghệ Hà Nội -> 5 topic
[137/1156] (school) Trường Đại học Công nghiệp Vinh -> 5 topic
[138/1156] (school) Đại Học Trà Vinh -> 4 topic
[139/1156] (school) Trường Đại Học Nông Lâm TPHCM -> 0 topic
[140/1156] (school) Học viện cán bộ TPHCM -> 3 topic
[141/1156] (school) Trường Đại Học Xây Dựng Hà Nội -> 1 topic
[142/1156] (school) Trường Đại Học Sư Phạm Kỹ Thuật Hưng Yên -> 3 topic
[143/1156] (school) Trường Đại Học Mở TPHCM -> 1 topic
[144/1156] (school) Trường Đại Học Tài Chính Ngân Hàng Hà Nội -> 0 topic
[145/1156] (school) Trường Đại học Công nghệ Giao thông vận tải -> 4 topic
[146/1156] (school) Trường Đại Học Mỏ Địa Chất -> 1 topic
[147/1156] (school) Trường Đại Học Điện Lực -> 3 topic
[148/1156] (school) Trường Đại Học Thể Dục Thể Thao TPHCM -> 2 topic
[149/1156] (school) Trường Đại Học Phương Đông -> 4 topic
[150/1156] (school) Trường Đại học Công nghệ kỹ thuật Vĩnh Long -> 1 topic
[151/1156] (school) Trường Đại Học Kiến Trúc Đà Nẵng -> 2 topic
[152/1156] (school) Trường Đại Học Kinh Doanh và Công Nghệ Hà Nội -> 3 topic
[153/1156] (school) Trường Đại Học Kỹ Thuật Công Nghiệp Thái Nguyên -> 4 topic
[154/1156] (school) Trường Đại Học Sư Phạm Thể Dục Thể Thao TPHCM -> 1 topic
[155/1156] (school) Trường Đại học Khánh Hòa -> 3 topic
[156/1156] (school) Trường Đại học Sư phạm Kỹ thuật - Đại học Đà Nẵng -> 1 topic
[157/1156] (school) Học Viện Ngân Hàng (Phân Viện Bắc Ninh) -> 1 topic
[158/1156] (school) Khoa Quốc tế - Đại học Huế -> 5 topic
[159/1156] (school) Trường Đại Học CMC -> 5 topic
[160/1156] (school) Trường Đại Học Nguyễn Tất Thành -> 5 topic
[161/1156] (school) Trường Đại Học Kinh Tế - Đại Học Huế -> 2 topic
[162/1156] (school) Trường Du Lịch - Đại Học Huế -> 3 topic
[163/1156] (school) Trường Sĩ Quan Không Quân - Hệ Đại học -> 1 topic
[164/1156] (school) Trường Đại học Công Nghệ Thông Tin và Truyền Thông Thái Nguyên -> 0 topic
[165/1156] (school) Trường Sĩ Quan Phòng Hóa -> 5 topic
[166/1156] (school) Trường Sĩ Quan Tăng - Thiết Giáp -> 5 topic
[167/1156] (school) Học Viện Quản Lý Giáo Dục -> 3 topic
[168/1156] (school) Đại Học Duy Tân -> 3 topic
[169/1156] (school) Trường Đại học Nam Cần Thơ -> 4 topic
[170/1156] (school) Trường Đại Học Quốc Tế Hồng Bàng -> 3 topic
[171/1156] (school) Trường Đại học Tân Tạo -> 5 topic
[172/1156] (school) Trường Đại Học Thể Dục Thể Thao Đà Nẵng -> 2 topic
[173/1156] (school) Trường Đại Học Cửu Long -> 1 topic
[174/1156] (school) Trường Đại Học Văn Lang -> 4 topic
[175/1156] (school) Trường Đại Học Phan Châu Trinh -> 5 topic
[176/1156] (school) Trường Đại Học Kinh Bắc -> 4 topic
[177/1156] (school) Trường Đại Học Hòa Bình -> 5 topic
[178/1156] (school) Trường Đại Học Đại Nam -> 5 topic
[179/1156] (school) Trường Đại Học Võ Trường Toản -> 2 topic
[180/1156] (school) Trường Đại Học Đông Á -> 5 topic
[181/1156] (school) Trường Sĩ Quan Công Binh - Hệ Quân sự - Đại học Ngô Quyền -> 0 topic
[182/1156] (school) Trường Sĩ Quan Đặc Công -> 2 topic
[183/1156] (school) Học viện Kỹ thuật và Công nghệ an ninh (Phía Bắc) -> 0 topic
[184/1156] (school) Học viện Kỹ thuật và Công nghệ an ninh (Phía Nam) -> 0 topic
[185/1156] (school) Trường Sĩ Quan Pháo Binh -> 5 topic
[186/1156] (school) Đại học Kinh Tế TPHCM - Phân hiệu Vĩnh Long -> 1 topic
[187/1156] (school) Trường Quản Trị và Kinh Doanh - ĐHQG Hà Nội -> 0 topic
[188/1156] (school) Trường Đại Học Việt Đức -> 5 topic
[189/1156] (school) Trường Đại Học Thủy Lợi (Cơ sở 2) -> 2 topic
[190/1156] (school) Trường Đại học Sao Đỏ -> 3 topic
[191/1156] (school) Trường Đại Học Phòng Cháy Chữa Cháy (phía Nam) -> 0 topic
[192/1156] (school) Học viện Phòng cháy chữa cháy và Cứu nạn cứu hộ -> 2 topic
[193/1156] (school) Phân hiệu Đại học Nông Lâm TPHCM tại Ninh Thuận -> 0 topic
[194/1156] (school) Trường Đại Học Tây Đô -> 5 topic
[195/1156] (school) Trường Đại học Công Nghệ TPHCM -> 5 topic
[196/1156] (school) Trường Đại Học Đông Đô -> 1 topic
[197/1156] (school) Trường Đại Học Lạc Hồng -> 5 topic
[198/1156] (school) Trường Đại Học Thành Đông -> 5 topic
[199/1156] (school) Trường Đại học Luật Huế -> 1 topic
[200/1156] (school) Trường Đại Học Yersin Đà Lạt -> 2 topic
[201/1156] (school) Trường Đại học Thành Đô -> 3 topic
[202/1156] (school) Trường Đại Học Bình Dương -> 5 topic
[203/1156] (school) Trường Đại Học Lương Thế Vinh -> 4 topic
[204/1156] (school) Trường Đại học Việt Nhật - ĐHQG Hà Nội -> 0 topic
[205/1156] (school) Trường Đại Học Bà Rịa – Vũng Tàu -> 2 topic
[206/1156] (school) Trường Đại Học Nghệ Thuật Huế -> 5 topic
[207/1156] (school) Trường Đại học Công nghệ Miền Đông -> 5 topic
[208/1156] (school) Trường Đại Học FPT -> 4 topic
[209/1156] (school) Trường Đại Học Kinh Tế Kỹ Thuật Bình Dương -> 4 topic
[210/1156] (school) Trường Đại Học Kinh Tế Tài Chính TPHCM -> 0 topic
[211/1156] (school) Trường Đại học Tài chính Quản trị kinh doanh -> 5 topic
[212/1156] (school) Trường Đại Học Tiền Giang -> 3 topic
[213/1156] (school) Trường Đại học Kinh tế và Quản trị kinh doanh Thái Nguyên -> 2 topic
[214/1156] (school) Trường Đại Học Dầu Khí Việt Nam -> 4 topic
[215/1156] (school) Trường Đại Học Ngoại Ngữ Tin Học TPHCM -> 0 topic
[216/1156] (school) Trường Đại Học Sư Phạm Kỹ Thuật Vinh -> 3 topic
[217/1156] (school) Trường Đại học Nghệ An -> 5 topic
[218/1156] (school) Trường Đại Học Lâm nghiệp -> 3 topic
[219/1156] (school) Trường Đại Học Văn Hiến -> 5 topic
[220/1156] (school) Trường Đại Học Quang Trung -> 5 topic
[221/1156] (school) Trường Đại Học Hoa Sen -> 5 topic
[222/1156] (school) Trường Đại Học Phan Thiết -> 5 topic
[223/1156] (school) Trường Đại Học Trưng Vương -> 5 topic
[224/1156] (school) Trường Đại Học Điều Dưỡng Nam Định -> 3 topic
[225/1156] (school) Trường Đại học Y khoa Tokyo Việt Nam -> 3 topic
[226/1156] (school) Trường Đại Học Công Nghệ Đồng Nai -> 5 topic
[227/1156] (school) Trường Đại Học Quốc Tế Miền Đông -> 5 topic
[228/1156] (school) Viện nghiên cứu và đào tạo Việt Anh - Đại học Đà Nẵng -> 1 topic
[229/1156] (school) Trường Đại Học Thể Dục Thể Thao Bắc Ninh -> 1 topic
[230/1156] (school) Khoa Kỹ thuật và Công nghệ - Đại học Huế -> 1 topic
[231/1156] (school) Trường Đại Học Thái Bình -> 5 topic
[232/1156] (school) Học Viện Dân Tộc -> 4 topic
[233/1156] (school) Trường Đại Học Khoa Học Huế -> 2 topic
[234/1156] (school) Trường Đại Học Khoa Học Thái Nguyên -> 1 topic
[235/1156] (school) Trường Đại Học Hồng Đức -> 3 topic
[236/1156] (school) Trường Đại Học Đồng Nai -> 4 topic
[237/1156] (school) Phân hiệu Đại Học Lâm nghiệp tại Đồng Nai -> 0 topic
[238/1156] (school) Trường Đại học Tài Nguyên và Môi Trường TPHCM -> 1 topic
[239/1156] (school) Trường Đại học Công nghiệp và Thương mại Hà Nội -> 1 topic
[240/1156] (school) Trường Đại Học Nguyễn Trãi -> 4 topic
[241/1156] (school) Trường Đại Học Công Nghiệp Việt Trì -> 1 topic
[242/1156] (school) Phân hiệu Đại học Quốc gia TPHCM tại Bến Tre -> 0 topic
[243/1156] (school) Trường Đại Học Nông Lâm Huế -> 3 topic
[244/1156] (school) Khoa Quốc Tế - Đại Học Thái Nguyên -> 5 topic
[245/1156] (school) Trường Đại học Quốc Tế Sài Gòn -> 5 topic
[246/1156] (school) Trường Đại học Intracom -> 1 topic
[247/1156] (school) Trường Đại Học Kinh Tế Công Nghiệp Long An -> 5 topic
[248/1156] (school) Trường Đại Học Quốc Tế Bắc Hà -> 4 topic
[249/1156] (school) Trường Đại Học Sư Phạm Kỹ Thuật Nam Định -> 3 topic
[250/1156] (school) Phân hiệu Đại học Nông Lâm TPHCM tại Gia Lai -> 0 topic
[251/1156] (school) Trường Đại Học Nông Lâm Thái Nguyên -> 1 topic
[252/1156] (school) Trường Đại học Quản lý và công nghệ TPHCM -> 3 topic
[253/1156] (school) Trường Đại Học Công Nghệ và Quản Lý Hữu Nghị -> 2 topic
[254/1156] (school) Phân Hiệu Đại Học Huế tại Quảng Trị -> 1 topic
[255/1156] (school) Trường Đại Học Thái Bình Dương -> 5 topic
[256/1156] (school) Trường Đại học Hùng Vương TPHCM -> 1 topic
[257/1156] (school) Trường Đại Học Kinh tế công nghệ Thái Nguyên -> 3 topic
[258/1156] (school) Trường Đại Học Phú Xuân -> 5 topic
[259/1156] (school) Trường Đại học Quản lý và Công nghệ Hải Phòng -> 4 topic
[260/1156] (school) Trường Đại Học Xây Dựng Miền Tây -> 4 topic
[261/1156] (school) Trường Đại Học Công Nghiệp Việt - Hung -> 2 topic
[262/1156] (school) Phân hiệu Đại học Lâm nghiệp tỉnh Gia Lai -> 0 topic
[263/1156] (school) Học Viện Ngân Hàng (Phân Viện Phú Yên) -> 1 topic
[264/1156] (school) Trường Đại học Tài Chính Kế Toán -> 2 topic
[265/1156] (school) Trường Đại Học Gia Định -> 5 topic
[266/1156] (school) Trường Đại Học Công Nghiệp Quảng Ninh -> 4 topic
[267/1156] (school) Trường Đại Học Xây Dựng Miền Trung -> 5 topic
[268/1156] (school) Trường Đại Học Công Nghệ Sài Gòn -> 5 topic
[269/1156] (school) Phân hiệu Đại học Xây dựng miền Trung tại Đà Nẵng -> 0 topic
[270/1156] (school) Trường Đại học Nông Lâm Bắc Giang -> 1 topic
[271/1156] (school) Trường Đại Học Tây Bắc -> 2 topic
[272/1156] (school) Trường Đại Học Đà Lạt -> 3 topic
[273/1156] (school) Phân Hiệu Đại Học Thái Nguyên Tại Lào Cai -> 1 topic
[274/1156] (school) Trường Đại học Tân Trào -> 5 topic
[275/1156] (school) Trường Đại học Kiên Giang -> 1 topic
[276/1156] (school) Trường Đại Học Văn Hóa, Thể Thao Và Du Lịch Thanh Hóa -> 5 topic
[277/1156] (school) Phân hiệu Đại học Thái Nguyên tại Hà Giang -> 0 topic
[278/1156] (school) Trường Đại Học Hoa Lư -> 5 topic
[279/1156] (school) Học Viện Âm Nhạc Huế -> 5 topic
[280/1156] (school) Học Viện Âm Nhạc Quốc Gia Việt Nam -> 4 topic
[281/1156] (school) Nhạc Viện TPHCM -> 1 topic
[282/1156] (school) Trường Đại Học Công Nghệ Vạn Xuân -> 2 topic
[283/1156] (school) Trường Đại Học Hà Hoa Tiên -> 5 topic
[284/1156] (school) Trường Đại Học Mỹ Thuật Công Nghiệp -> 5 topic
[285/1156] (school) Trường Đại Học Mỹ Thuật TPHCM -> 2 topic
[286/1156] (school) Trường Đại Học Mỹ Thuật Việt Nam -> 5 topic
[287/1156] (school) Trường Đại Học Sân Khấu Điện Ảnh Hà Nội -> 0 topic
[288/1156] (school) Trường Đại học Văn hóa Nghệ thuật Quân đội -> 2 topic
[289/1156] (school) Trường Đại học Nội vụ Hà Nội -> 4 topic
[290/1156] (school) Trường Sĩ Quan Kĩ Thuật Quân Sự - Hệ Quân sự - Đại Học Trần Đại Nghĩa -> 0 topic
[291/1156] (school) Trường Đại Học Sân Khấu Điện Ảnh TPHCM -> 1 topic
[292/1156] (school) Trường Đại Học Công Nghệ Đông Á -> 5 topic
[293/1156] (school) Trường Đại học Y Dược Buôn Ma Thuột -> 2 topic
[294/1156] (school) Khoa Giáo dục thể chất Đà Nẵng -> 1 topic
[295/1156] (school) Trường Đại học Công nghệ Thông tin và Truyền thông Việt Hàn - Đại học Đà Nẵng -> 1 topic
[296/1156] (school) Trường Đại Học Phòng Cháy Chữa Cháy (Hệ Dân sự Phía Bắc) -> 0 topic
[297/1156] (school) Học Viện Hậu Cần - Hệ Dân sự -> 1 topic
[298/1156] (school) Học Viện Khoa Học Quân Sự - Hệ Dân sự -> 3 topic
[299/1156] (school) Học Viện Kỹ Thuật Quân Sự - Hệ Dân sự -> 4 topic
[300/1156] (school) Trường Sĩ Quan Thông Tin - Hệ Dân Sự - Đại Học Thông Tin Liên Lạc -> 0 topic
[301/1156] (school) Học Viện Quân Y - Hệ Dân sự -> 4 topic
[302/1156] (school) Trường Đại Học Phòng Cháy Chữa Cháy (Hệ Dân sự Phía Nam) -> 0 topic
[303/1156] (major_group) Kế toán - Kiểm toán -> 5 topic
[304/1156] (major_group) Tài chính - Ngân hàng - Bảo hiểm -> 0 topic
[305/1156] (major_group) Kinh tế - Quản trị kinh doanh - Thương Mại -> 4 topic
[306/1156] (major_group) Công nghệ thông tin - Tin học -> 5 topic
[307/1156] (major_group) Công nghiệp bán dẫn -> 5 topic
[308/1156] (major_group) Báo chí - Marketing - Quảng cáo - PR -> 0 topic
[309/1156] (major_group) Sư phạm - Giáo dục -> 2 topic
[310/1156] (major_group) Y - Dược -> 5 topic
[311/1156] (major_group) Bác sĩ thú y -> 5 topic
[312/1156] (major_group) Công an - Quân đội -> 0 topic

# 6. Kiểm tra kết quả

In [26]:
# Khảo sát dữ liệu sau khi lưu
df_topics.info()
df_topics.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 3579 entries, 0 to 3578
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   keyword       3579 non-null   str
 1   keyword_type  3579 non-null   str
 2   mid           3579 non-null   str
 3   title         3579 non-null   str
 4   type          3579 non-null   str
dtypes: str(5)
memory usage: 529.1 KB

,keyword,keyword_type,mid,title,type
0,Trường Cao Đẳng Kỹ Thuật Cao Thắng,school,/g/122jr9l6,Trường Cao đẳng Kỹ thuật Cao Thắng,"Trường cao đẳng nghề ở Thành phố Hồ Chí Minh, ..."
1,Trường Cao Đẳng Kỹ Thuật Cao Thắng,school,/g/11c6v9lswf,Thư viện trường Cao đẳng kỹ thuật Cao Thắng,"Thư viện đại học ở Thành phố Hồ Chí Minh, Việt..."
2,Trường Cao Đẳng Kỹ Thuật Cao Thắng,school,/g/11gw35hb5j,Ga Hàm Nghi,Chủ đề
3,Trường Cao Đẳng Công Thương TPHCM,school,/m/0vb4j37,Cao Đẳng Công Thương TP.HCM,"Cao đẳng ở Thành phố Hồ Chí Minh, Việt Nam"
4,Trường Cao Đẳng Công Thương TPHCM,school,/m/0vb3q34,Trường Đại học Công Thương TP. Hồ Chí Minh (HUIT),"Đại học ở Thành phố Hồ Chí Minh, Việt Nam"
5,Trường Cao Đẳng Công Thương TPHCM,school,/g/11bx2lgy79,Trường Cao đẳng Lý Tự Trọng TP. Hồ Chí Minh,Trường cao đẳng cộng đồng ở Thành phố Hồ Chí M...
6,Trường Cao Đẳng Công Thương TPHCM,school,/g/11c5szrcxf,Danh sách trường cao đẳng tại Thành phố Hồ Chí...,Chủ đề
7,Đại Học Kinh Tế Quốc Dân,school,/m/0bwj_9k,Trường Đại học Kinh tế Quốc dân,"Đại học công lập ở Hà Nội, Việt Nam"
8,Đại Học Kinh Tế Quốc Dân,school,/m/02q6bnb,Plekhanov Russian University of Economics,"Trường đại học ở Mát-xcơ-va, Nga"
9,Đại Học Kinh Tế Quốc Dân,school,/g/11h03bdz2j,Đại học Từ xa - Đại Học Kinh Tế Quốc Dân,"Trung tâm giáo dục ở Hà Nội, Việt Nam"

In [27]:
# Thống kê theo loại keyword và loại topic
print(df_topics.groupby('keyword_type')['keyword'].nunique())
print(df_topics['type'].value_counts().head(10))
print(f"Keyword không có topic: {len(no_result)}")

keyword_type
admission_method      5
major               422
major_group          32
school              268
subject              65
subject_group       135
Name: keyword, dtype: int64
type
Chủ đề                                              1264
Lĩnh vực nghiên cứu                               193
Trường đại học ở Hà Nội, Việt Nam                    115
Phần mềm                                             112
Phần mềm máy tính                                     83
Nghề nghiệp                                           79
Trường đại học ở Thành phố Hồ Chí Minh, Việt Nam      76
Dòng sản phẩm                                      69
Cơ quan chính phủ                                     55
Đại học ở Thành phố Hồ Chí Minh, Việt Nam           46
Name: count, dtype: int64
Keyword không có topic: 229

# 7. Xuất Notebook sang Unit Script

In [28]:
from helpers.export_to_script import export_to_script

export_to_script(output_path=SCRIPT_OUTPUT_PATH)

Đã xuất 7 cell từ 'get_topics.ipynb' sang 'D:\UNIDOCS\IS405.R11-Big-Data\scripts-fetching\unit-scripts\get_topics.py'

'D:\\UNIDOCS\\IS405.R11-Big-Data\\scripts-fetching\\unit-scripts\\get_topics.py'